[package]
name = "es-combustion"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Combustion chamber, fuel, ignition module"

[dependencies]
es-units = { path = "../es-units" }
es-function = { path = "../es-function" }
es-gas = { path = "../es-gas" }
es-mechanics = { path = "../es-mechanics" }
es-solver = { path = "../es-solver" }
